### ISSUE TITLE
Task 0 checklist

### ISSUE THREAD

**Issue by Moscuuu** [Moscuuu/Programming-Technologies-tasks-by-AM-MW#2]
- [ ] the task provides required feedback and has been submitted (needs grading)
- [ ] the ability to clone the repository to the teacher's computer
- [ ] `README.md` contains required information
- [ ] build succeeded
- [ ] all UT's are green
